<?xml version="1.0"?>

<st-source>
<time-stamp>From VisualWorks® NonCommercial, 7.6 of lundi 3 mars 2008 on mardi 22 septembre 2020 at 4:27:51</time-stamp>
<!-- Package CormasCovid* -->


<name-space>
<name>CormasCovid</name>
<environment>CormasNS.Models</environment>
<private>false</private>
<imports>
			private Smalltalk.*
			private CormasNS.Kernel.*
			</imports>
<category>CormasCovidCategory</category>
<attributes>
<package>CormasCovid</package>
</attributes>
</name-space>

<class>
<name>CormasCovid</name>
<environment>CormasNS.Models.CormasCovid</environment>
<super>CormasNS.Kernel.CormasModel</super>
<private>false</private>
<indexed-type>none</indexed-type>
<inst-vars></inst-vars>
<class-inst-vars></class-inst-vars>
<imports></imports>
<category>CormasCovidCategory</category>
<attributes>
<package>CormasCovid</package>
</attributes>
</class>



<methods>
<class-id>CormasNS.Models.CormasCovid.CormasCovid class</class-id> <category>description</category>

<body package="CormasCovid">creationDate
^ 'mardi 22 septembre 2020'</body>

<body package="CormasCovid">version
^ 'CormasCovid.st'</body>

<body package="CormasCovid">currentDeveloperName
^ 'MissAbms2020'</body>

<body package="CormasCovid">versionComments
^ ' 

 --------------------- CormasCovid.st --------------------- Date: 2020.3.31
Firs model saving
 *** Developer: MissAbms2020 ***'</body>

<body package="CormasCovid">emails
^ '"miss-abms trainers" &lt;miss-abms_trainers@agropolis.fr&gt;'</body>

<body package="CormasCovid">authors
^ 'MissAbms2020'</body>

<body package="CormasCovid">lastUpdate
^ 'mardi 22 septembre 2020'</body>

<body package="CormasCovid">comments
^ 'See github repository: https://github.com/MISS-ABMS/CormasCovid'</body>
</methods>


<methods>
<class-id>CormasNS.Models.CormasCovid.CormasCovid</class-id> <category>instance-creation</category>

<body package="CormasCovid">initAgents
"To be completed"</body>
</methods>

<methods>
<class-id>CormasNS.Models.CormasCovid.CormasCovid</class-id> <category>init</category>

<body package="CormasCovid">init
"To be completed"
	self initCells.</body>
</methods>

<methods>
<class-id>CormasNS.Models.CormasCovid.CormasCovid</class-id> <category>control</category>

<body package="CormasCovid">step: t
"To be completed"</body>
</methods>




</st-source>
